image:
  repository: ghcr.io/<your-username>/go-web-app
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests: { cpu: "50m", memory: "64Mi" }
  limits:   { cpu: "200m", memory: "256Mi" }

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []
