apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  namespace: go-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: go-web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-web-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet: { path: /home, port: 8080 }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /home, port: 8080 }
            initialDelaySeconds: 10
          resources:
            requests: {{ toYaml .Values.resources.requests | nindent 12 }}
            limits:   {{ toYaml .Values.resources.limits | nindent 12 }}
