image:
  tag: "prod"
replicaCount: 3
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: app.example.com
      paths: ["/"]
  tls:
    - secretName: app-tls
      hosts: ["app.example.com"]
