apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  namespace: go-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: go-web-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-web-app
    spec:
      containers:
        - name: app
          image: go-web-app:dev   # will replace with GHCR image later
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /home
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
