name: CI - Build, Push, Bump Tag
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Unit tests
        run: |
          cd app
          go test ./...

      - name: Compute image vars (lowercase owner + short sha)
        id: vars
        run: |
          echo "IMAGE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR (via GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_OWNER }}/go-web-app:${{ github.sha }}
            ghcr.io/${{ env.IMAGE_OWNER }}/go-web-app:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Bump Helm dev tag to current SHA
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s/^  tag: \".*\"/  tag: \"${SHORT_SHA}\"/" helm/go-web-app/env/values-dev.yaml
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add helm/go-web-app/env/values-dev.yaml
          git commit -m "ci: bump dev image tag to ${SHORT_SHA}" || echo "No changes"
          git push
